/**
 * 2ine; an OS/2 emulator for Linux.
 *
 * Please see the file LICENSE.txt in the source's root directory.
 */

/* THIS FILE IS AUTOGENERATED. DO NOT EDIT BY HAND. see lxapigen.pl */

/* This is glue code for OS/2 binaries. Native binaries don't need this. */
#if LX_LEGACY

LX_NATIVE_MODULE_INIT()
    LX_NATIVE_EXPORT(DosQueryCtryInfo, 5),
    LX_NATIVE_EXPORT(DosQueryDBCSEnv, 6),
    LX_NATIVE_EXPORT(DosMapCase, 7)
LX_NATIVE_MODULE_INIT_END()

#endif /* LX_LEGACY */

/* end of nls-lx.h ... */

