/**
 * 2ine; an OS/2 emulator for Linux.
 *
 * Please see the file LICENSE.txt in the source's root directory.
 */

/* THIS FILE IS AUTOGENERATED. DO NOT EDIT BY HAND. see lxapigen.pl */

/* This is glue code for OS/2 binaries. Native binaries don't need this. */
#if LX_LEGACY

LX_NATIVE_MODULE_INIT()
    LX_NATIVE_EXPORT(WinBeginPaint, 703),
    LX_NATIVE_EXPORT(WinCreateMsgQueue, 716),
    LX_NATIVE_EXPORT(WinDestroyMsgQueue, 726),
    LX_NATIVE_EXPORT(WinDestroyWindow, 728),
    LX_NATIVE_EXPORT(WinEndPaint, 738),
    LX_NATIVE_EXPORT(WinFillRect, 743),
    LX_NATIVE_EXPORT(WinGetLastError, 753),
    LX_NATIVE_EXPORT(WinInitialize, 763),
    LX_NATIVE_EXPORT(WinIsWindow, 772),
    LX_NATIVE_EXPORT(WinIsWindowEnabled, 773),
    LX_NATIVE_EXPORT(WinIsWindowVisible, 775),
    LX_NATIVE_EXPORT(WinTerminate, 888),
    LX_NATIVE_EXPORT(WinPostQueueMsg, 902),
    LX_NATIVE_EXPORT(WinCreateStdWindow, 908),
    LX_NATIVE_EXPORT(WinCreateWindow, 909),
    LX_NATIVE_EXPORT(WinDefWindowProc, 911),
    LX_NATIVE_EXPORT(WinDispatchMsg, 912),
    LX_NATIVE_EXPORT(WinGetMsg, 915),
    LX_NATIVE_EXPORT(WinPostMsg, 919),
    LX_NATIVE_EXPORT(WinSendMsg, 920),
    LX_NATIVE_EXPORT(WinRegisterClass, 926)
LX_NATIVE_MODULE_INIT_END()

#endif /* LX_LEGACY */

/* end of pmwin-lx.h ... */

