/**
 * 2ine; an OS/2 emulator for Linux.
 *
 * Please see the file LICENSE.txt in the source's root directory.
 */

/* THIS FILE IS AUTOGENERATED. DO NOT EDIT BY HAND. see lxapigen.pl */

/* This is glue code for OS/2 binaries. Native binaries don't need this. */
#if LX_LEGACY

LX_NATIVE_MODULE_INIT()
    LX_NATIVE_EXPORT(DosReadQueue, 9),
    LX_NATIVE_EXPORT(DosPurgeQueue, 10),
    LX_NATIVE_EXPORT(DosCloseQueue, 11),
    LX_NATIVE_EXPORT(DosQueryQueue, 12),
    LX_NATIVE_EXPORT(DosPeekQueue, 13),
    LX_NATIVE_EXPORT(DosWriteQueue, 14),
    LX_NATIVE_EXPORT(DosOpenQueue, 15),
    LX_NATIVE_EXPORT(DosCreateQueue, 16)
LX_NATIVE_MODULE_INIT_END()

#endif /* LX_LEGACY */

/* end of quecalls-lx.h ... */

